### ISSUE TITLE
dataset question

### ISSUE THREAD

**Issue by YhQIAO** [gitouni/CalibNet_pytorch#7]
why i got these messages:
  Ground truth poses are not avaialble for sequence 11.
  Ground truth poses are not avaialble for sequence 12.
  Ground truth poses are not avaialble for sequence 13.
when i run test.py?
it seems that kitti dataset dosen't have ground truth poses of sequence 11-22?

**Comment by gitouni** [comment]
You don't need to worry about this. It's just a moderate warning from `pykitti` module.

https://github.com/gitouni/CalibNet_pytorch/blob/25fdfa519ea0963d80ad76a0817af886cb144442/dataset.py#L116-L116

The ground-truth poses of sequence 11-20 are not provided by KITTI because these sequences are used for fair testing, and that is why the `pykitti.odometry()` threw that warning. However, it does not affect the calibration process, so do not worry about that.

**Comment by zzq123zz** [comment]
how can i get the poses in the dataset?

**Comment by gitouni** [comment]
> how can i get the poses in the dataset?

We all have no access to the poses of sequences for testing. They're used for online evaluation of odometry performance.

**Comment by zzq123zz** [comment]
How the poses is obtained in the figure below？
















At 2023-09-13 17:46:03, "gitouni" ***@***.***> wrote:

how can i get the poses in the dataset?

We all have no access to the poses of sequences for testing. They're used for online evaluation of odometry performance.

**Comment by gitouni** [comment]
> How the poses is obtained in the figure below？ At 2023-09-13 17:46:03, "gitouni" ***@***.***> wrote: how can i get the poses in the dataset? We all have no access to the poses of sequences for testing. They're used for online evaluation of odometry performance. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Sorry, I cannot see that figure that you want to display. However, the poses are not necessary for this calibration, as CalibNet works on a single-frame mode.

**Comment by zzq123zz** [comment]
I have resulted! Thank you!



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 09/14/2023 09:34 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [gitouni/CalibNet_pytorch] dataset question (Issue #7) |

How the poses is obtained in the figure below？ At 2023-09-13 17:46:03, "gitouni" @.> wrote: how can i get the poses in the dataset? We all have no access to the poses of sequences for testing. They're used for online evaluation of odometry performance. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

Sorry, I cannot see that figure that you want to display. However, the poses are not necessary for this calibration, as CalibNet works on a single-frame mode.
